---
RuhohSpec: '0.2'

theme : twitter
permalink: /:categories/:title

production_url : http://jasonm23.ruhoh.com

comments :
  provider : disqus
  disqus :
    short_name : codefodder

syntax :
  provider : google_prettify
  google_prettify : 
      theme: sunburst-custom
      linenums : true